[window]

opacity = 0.5
blur = true
padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 15.0

[env]
TERM = "xterm-256color"

[general]
import = [ "~/.config/alacritty/catppuccin/catppuccin-mocha.toml" ]
